# This is the workflow to use for everyday code changes.
name: Publish
on:
  push:
    branches:
      - '!*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
      - name: Configure node
        run: npm config set scripts-prepend-node-path true
      - name: Install dependencies
        run: yarn install
      - name: Rebuild
        run: yarn run rebuild
      - name: Lint & test
        run: yarn run check
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
          chmod u+x ./publish.sh
          ./publish.sh
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
